from enum import Enum

class WeightGoalEnum(Enum):
    BAJAR = "bajar"
    MANTENER = "mantener"
    SUBIR = "subir"

class BodyPartEnum(Enum):
    NECK = "Cuello"
    LOWER_ARMS = "Antebrazos"
    SHOULDERS = "Hombros"
    CARDIO = "Cardio"
    UPPER_ARMS = "Brazos"
    CHEST = "Pecho"
    LOWER_LEGS = "Pantorrillas"
    BACK = "Espalda"
    UPPER_LEGS = "Muslos"
    WAIST = "Cintura"

class EquipmentEnum(Enum):
    ASSISTED = "Asistido"
    BAND = "Banda de resistencia"
    BARBELL = "Barra"
    BATTLING_ROPE = "Cuerda de batalla"
    BODYWEIGHT = "Peso corporal"
    BOSUBALL = "Bola bosu"
    CABLE = "Polea"
    DUMBBELL = "Mancuerna"
    EZBARBELL = "Barra ez"
    HAMMER = "Martillo"
    KETTLEBELL = "Pesa rusa"
    LEVERAGE_MACHINE = "Máquina de palanca"
    MEDICINE_BALL = "Balón medicinal"
    OLYMPIC_BARBELL = "Barra olímpica"
    POWERSLED = "Trineo de potencia"
    RESISTANCE_BAND = "Banda elástica"
    ROLL = "Rodillo"
    ROLLBALL = "Pelota de rodillo"
    ROPE = "Cuerda"
    SLEDMACHINE = "Máquina de trineo"
    SMITHMACHINE = "Máquina smith"
    STABILITY_BALL = "Pelota de estabilidad"
    STICK = "Palo"
    SUSPENSION = "Suspensión"
    TRAPBAR = "Barra hexagonal"
    VIBRATEPLATE = "Plataforma vibratoria"
    WEIGHTED = "Con peso"
    WHEELROLLER = "Rueda abdominal"

class ExerciseTypeEnum(Enum):
    FUERZA = "Fuerza"
    CARDIO = "Cardio"
    PLIOMETRÍA = "Pliometría"
    ESTIRAMIENTO = "Estiramiento"
    LEVANTAMIENTO_DE_PESAS = "Levantamiento de pesas"
    YOGA = "Yoga"
    AERÓBICOS = "Aeróbicos"
    
class MuscleEnum(Enum):
    SHINS = "Espinillas"
    HANDS = "Manos"
    STERNOCLEIDOMASTOID = "Esternocleidomastoideo"
    SOLEUS = "Soleo"
    INNER_THIGHS = "Muslos internos"
    LOWER_ABS = "Abdomen inferior"
    GRIP_MUSCLES = "Músculos de agarre"
    ABDOMINALS = "Abdominales"
    WRIST_EXTENSORS = "Extensores de la muñeca"
    WRIST_FLEXORS = "Flexores de la muñeca"
    LATISSIMUS_DORSI = "Dorsal ancho"
    UPPER_CHEST = "Pecho superior"
    ROTATOR_CUFF = "Manguito rotador"
    WRISTS = "Muñecas"
    GROIN = "Ingle"
    BRACHIALIS = "Braquial"
    DELTOIDS = "Deltoides"
    FEET = "Pies"
    ANKLES = "Tobillos"
    TRAPEZIUS = "Trapecio"
    REAR_DELTOIDS = "Deltoides posteriores"
    CHEST = "Pecho"
    QUADRICEPS = "Cuádriceps"
    BACK = "Espalda"
    CORE = "Core"
    SHOULDERS = "Hombros"
    ANKLE_STABILIZERS = "Estabilizadores del tobillo"
    RHOMBOIDS = "Romboides"
    OBLIQUES = "Oblicuos"
    LOWER_BACK = "Espalda baja"
    HIP_FLEXORS = "Flexores de cadera"
    LEVATOR_SCAPULAE = "Elevador de la escápula"
    ABDUCTORS = "Abductores"
    SERRATUS_ANTERIOR = "Serrato anterior"
    TRAPS = "Trapecios"
    FOREARMS = "Antebrazos"
    DELTS = "Deltas"
    BICEPS = "Bíceps"
    UPPER_BACK = "Espalda alta"
    SPINE = "Columna"
    CARDIOVASCULAR_SYSTEM = "Sistema cardiovascular"
    TRICEPS = "Tríceps"
    ADDUCTORS = "Aductores"
    HAMSTRINGS = "Isquiotibiales"
    GLUTES = "Glúteos"
    PECTORALS = "Pectorales"
    CALVES = "Pantorrillas"
    LATS = "Dorsales"
    QUADS = "Cuádriceps"
    ABS = "Abdominales"